// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ogyacwhpezaqrrccykuz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9neWFjd2hwZXphcXJyY2N5a3V6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2MTA4NzAsImV4cCI6MjA2NjE4Njg3MH0.VKueVOTEnq-TAHOdQfNZUJEWLvuKOtT6aMwOrQMptXo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);