// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gnmqmkdjtlqkeuwjkabq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdubXFta2RqdGxxa2V1d2prYWJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2MTA1NjEsImV4cCI6MjA2NjE4NjU2MX0.HO_10xKu-AYSB18VvWmxHgKYm-uYLgFz2lCwYmSQ0GI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);